name: tfg_monetracker_leireyafer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.2
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: any
  path: ^1.9.0
  fl_chart: ^0.70.2
  flutter_colorpicker: ^1.1.0
  http: any
  #Firebase dependencies
  firebase_core: ^3.13.0 #paquete base para usar Firebase 
  firebase_auth: ^5.5.2 #autenticación de usuarios
  cloud_firestore: ^5.6.6 #acceso a la base de datos NoSQL. Permite almacenar, consultar y sincronizar datos en tiempo real
  flutter_secure_storage: ^9.2.4 #guardar datos sensibles de forma segura en el dispositivo, como credenciales
  logger: any #mensaje en consola

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 #el editor o el compilador avisa de problemas o sugerencias

flutter:
  uses-material-design: true
  #añadir esto
  generate: true
  assets:
    - assets/currencies.json